### ISSUE TITLE
user.posts.feed

### ISSUE THREAD

**Issue by wweevv-johndpope** [sheldygg/aiotiktok#6]
https://tikapi.io/documentation/#tag/Posts/operation/user.posts.feed
 this solution requires api key  + it can successfully get the user feeds given a login. 

<img width="510" alt="Screenshot 2023-05-29 at 3 45 04 pm" src="https://github.com/sheldygg/aiotiktok/assets/109928647/e1ddf8a6-2626-464b-914d-5168c940eb85">

I think they're using some private api - as this is not generally available. 
if there's any pointers you have - or how can we make a private api call ? is that related to your other repo?

**Comment by sheldygg** [comment]
most likely they use a private tiktok api, in my code I do the [same](https://github.com/sheldygg/aiotiktok/blob/main/aiotiktok/client.py#L156), but without authorization, you just must up this https://github.com/sheldygg/tiktok-signature

**Comment by wweevv-johndpope** [comment]
Thanks again. I found a bunch of private api urls from github - /aweme/v2 - if there's interest I can help collate.

**Comment by sheldygg** [comment]
if you have method to get user info i would watch cause i not like [this](https://github.com/sheldygg/aiotiktok/blob/main/aiotiktok/client.py#LL109C20-L109C20) realisation

**Comment by wweevv-johndpope** [comment]
maybe this one?
https://github.com/xtekky/TikTok-Report-Bot/blob/af7cbe88b499dcd25f03156e9aeac81d50133745/utils/api.py#L123

```python
  def user_info(this, uniqueId: str) -> response:
        params = this.get_params({
            'uniqueId': uniqueId
        })

        return this.client.get(f'https://www.tiktok.com/api/user/detail/?{this.sign(params, this.userAgent)}', headers = this.get_headers(), cookies = this.cookies)
    

other calls I dug up just searching github for /aweme/v2

```
https://github.com/liujian0413/tiktok-src/blob/90f305b5f981d39cfb313d75ab231326c9fca597/sources/com/p280ss/android/ugc/aweme/discover/api/SearchApi.java

```java
@C7730f(mo20420a = "/aweme/v1/hot/search/video/list/")
    C7492s<Object> getAwemesByHotWord(@C7744t(mo20436a = "hotword") String str, @C7744t(mo20436a = "offset") int i, @C7744t(mo20436a = "count") int i2, @C7744t(mo20436a = "source") String str2, @C7744t(mo20436a = "is_ad") int i3, @C7744t(mo20436a = "gid") String str3, @C7744t(mo20436a = "item_id_list") String str4, @C7744t(mo20436a = "is_trending") int i4);

    @C7730f(mo20420a = "/aweme/v1/hot/search/list/")
    C7492s<HotSearchListResponse> getHotSearchList(@C7744t(mo20436a = "detail_list") Integer num, @C7744t(mo20436a = "mac_address") String str, @C7744t(mo20436a = "source") Integer num2, @C7744t(mo20436a = "current_word") String str2, @C7744t(mo20436a = "words_in_panel") String str3, @C7744t(mo20436a = "trend_entry_word") String str4);

    @C7730f(mo20420a = "/aweme/v1/hotsearch/aweme/billboard/")
    C7492s<HotVideoListResponse> getHotVideoList();

    @C7730f(mo20420a = "/aweme/v1/branch/billboard/entrance/")
    C7492s<RankingListCover> getRankingListCover();

    @C7729e
    @C7739o(mo20429a = "/aweme/v1/search/item/")
    C7492s<SearchMix> searchFeedList(@C7727c(mo20417a = "keyword") String str, @C7727c(mo20417a = "offset") long j, @C7727c(mo20417a = "count") int i, @C7727c(mo20417a = "source") String str2, @C7727c(mo20417a = "is_pull_refresh") int i2, @C7727c(mo20417a = "hot_search") int i3, @C7727c(mo20417a = "search_id") String str3, @C7727c(mo20417a = "query_correct_type") int i4);



public interface DiscoverService {
        @C6457h(mo15740a = "/aweme/v2/discovery/v4/category/list/")
        C7492s<DiscoverV4CategoryResponse> categoryListV4(@C6474y(mo15757a = "category_list_type") int i);

        @C6457h(mo15740a = "/aweme/v1/discover/cell/detail/")
        C1592h<DiscoverCellDetailResponse> cellDetail(@C6474y(mo15757a = "type") int i, @C6474y(mo15757a = "is_recommend") boolean z, @C6474y(mo15757a = "cell_id") String str);

        @C6457h(mo15740a = "/aweme/v2/discovery/v4/cell/detail/")
        C1592h<DiscoveryV4CellDetailResponse> cellDetailV4(@C6474y(mo15757a = "ab_type") int i, @C6474y(mo15757a = "cell_id") String str, @C6474y(mo15757a = "tab_name") String str2, @C6474y(mo15757a = "count") int i2);

        @C6457h(mo15740a = "/aweme/v2/discovery/cell/list/")
        C7492s<DiscoveryV3CellListResponse> cellListV3(@C6474y(mo15757a = "cursor") int i, @C6474y(mo15757a = "count") int i2, @C6474y(mo15757a = "ab_type") int i3);

        @C6457h(mo15740a = "/aweme/v2/discovery/v4/cell/list/")
        C7492s<DiscoverV4PlayListResponse> cellListV4(@C6474y(mo15757a = "cursor") int i, @C6474y(mo15757a = "count") int i2, @C6474y(mo15757a = "tab_name") String str, @C6474y(mo15757a = "ab_type") int i3);

        @C6457h(mo15740a = "/aweme/v1/discover/cell/list/")
        C1592h<DiscoverCellSectionListResponse> cellSectionList();

        @C6457h(mo15740a = "/aweme/v1/recommend/user/dislike/")
        C12466b<String> disLikeRecommend(@C6474y(mo15757a = "user_id") String str);

        @C6457h(mo15740a = "/aweme/v1/find/")
        C12466b<BannerList> fetchBanners(@C6475z Map<String, String> map);

        @C6457h
        C12466b<CategoryList> fetchCategoryList(@C6450ac String str, @C6475z Map<String, String> map);

        @C6457h(mo15740a = "/aweme/v1/hot/search/")
        C12466b<WideSearchResponse> fetchHotSearch();

        @C6457h(mo15740a = "/aweme/v2/discovery/v4/trending/")
        C7492s<DiscoverTrendingReponseV4> trendingListV4(@C6474y(mo15757a = "trending_type") int i, @C6474y(mo15757a = "cursor") int i2, @C6474y(mo15757a = "count") int i3);
    }


 static {
        StringBuilder sb = new StringBuilder();
        sb.append(Api.f60502b);
        sb.append("/aweme/v1/category/list/");
        f70050a = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(Api.f60502b);
        sb2.append("/aweme/v2/category/list/");
        f70051b = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append(Api.f60502b);
        sb3.append("/aweme/v1/category/fascinating/list/");
        f70052c = sb3.toString();

   @C7730f(mo20420a = "/api/suggest_words/")
    C1592h<SuggestWordResponse> getRecommendWords(@C7744t(mo20436a = "from_group_id") String str, @C7744t(mo20436a = "query") String str2, @C7744t(mo20436a = "business_id") String str3);

    @C7730f(mo20420a = "/api/suggest_words/")
    C1592h<SuggestWordResponse> getSuggestWords(@C7744t(mo20436a = "business_id") String str, @C7744t(mo20436a = "from_group_id") String str2, @C7744t(mo20436a = "word_in_box") String str3);

    @C7730f(mo20420a = "/api/suggest_words/")
    C1592h<String> getSuggestWordsWithRawString(@C7744t(mo20436a = "business_id") String str, @C7744t(mo20436a = "from_group_id") String str2, @C7744t(mo20436a = "word_in_box") String str3);


    public interface RealApi {
        @C7730f(mo20420a = "/aweme/v1/challenge/suggested/")
        C1592h<SuggestChallengeResponse> getSuggestChallenges();

        @C7730f(mo20420a = "/aweme/v1/music/suggested/")
        C1592h<SuggestMusicResponse> getSuggestMusics();

        @C7730f(mo20420a = "/aweme/v1/user/suggested/")
        C1592h<SuggestUserResponse> getSuggestUsers();
    }

 public interface FeedbackMessage {
        @C6456g
        @C6468s(mo15750a = "/feedback/2/post_message/")
        C18253l<String> postMessage(@C6455f Map<String, String> map);
    }
```

**Comment by wweevv-johndpope** [comment]
so I ran your code
```python


import asyncio
from aiotiktok import Client

tiktok = Client(signature_url="http://111.111.111.111:8002/signature")


async def main():
   test =  await tiktok.user_feed_sig("playboicarti")
   print("test:",test)

asyncio.run(main())

```

I get 2 results - 


test: [VideoData(url='https://www.tiktok.com/@playboicarti/video/6914381455640530181', video_type=<VideoType.VIDEO: 'video'>, media=Video(url='https://v16m-default.akamaized.net/5ab5f698ad41fb2394f083c3ba32d1f5/64774310/video/tos/useast2a/tos-useast2a-ve-0068c001/13ee878c0e3041528c1cc83b06110823/?a=0&ch=0&cr=0&dr=0&lr=all&cd=0%7C0%7C0%7C0&cv=1&br=2164&bt=1082&cs=0&ds=6&ft=XE5bCq1hmI1LD12NE41vG-UxaiJ6MVF_O5&mime_type=video_mp4&qs=0&rc=PGc5Ozk1NTo3ZDxlOmZlPEBpajg8NDQ5dW9neTMzPDczM0BiMS02LWMuXjExMS4zMV40YSNtZS4ucGU0L25fLS0tMTZzcw%3D%3D&l=20230531065214D626D7CD49B68065B464&btag=e00080000'), cover='https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068/86cb3cc84605409e9763878e1c9b1172~noop.image?x-expires=1685599200&x-signature=h%2F9Sqk2JZwM8s3P%2B%2FaX%2FExQp8SM%3D&s=FEED&se=false&sh=&sc=cover&l=20230531065214D626D7CD49B68065B464', dynamic_cover='https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/af7717115736400da6339523e128d97e_1609879901?x-expires=1685599200&x-signature=jZhn4eR3YO%2F9iEX0YwW0KHEjy4A%3D&s=FEED&se=false&sh=&sc=dynamic_cover&l=20230531065214D626D7CD49B68065B464', description='OMFg oMg 0mG > r3D r3d REd > .', statistics=Statistics(likes=918179, plays=6300741, comments=24297, downloads=16758, shares=38421491, saves=48737), create_time=1609879899, author=Author(unique_id='playboicarti', nickname='playboicarti', avatar='https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/17961639c0042c3c205f9da21a5ac859~c5_1080x1080.webp?x-expires=1685599200&x-signature=h1aFxdPxjPkBzRGvjeOyQllsrKE%3D', id=None, sec_uid='MS4wLjABAAAAM91LHXSoQbzIiQyAKL0LMg43mcyNQ9e32m8LJGKWZdo8RrWz0MveuIZyl0rkWtOs'), music=Music(title='original sound - playboicarti', author='playboicarti', url='https://sf16-ies-music-va.tiktokcdn.com/obj/musically-maliva-obj/6914381446920669957.mp3', cover='https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/17961639c0042c3c205f9da21a5ac859~c5_1080x1080.webp?x-expires=1685599200&x-signature=h1aFxdPxjPkBzRGvjeOyQllsrKE%3D')), VideoData(url='https://www.tiktok.com/@playboicarti/video/6909227930145082629', video_type=<VideoType.VIDEO: 'video'>, media=Video(url='https://v16m-default.akamaized.net/0248c124da61e42a37f1f45e63aa6c33/64774312/video/tos/useast2a/tos-useast2a-ve-0068c002/517dfdafdb67409c96324be4289d82fe/?a=0&ch=0&cr=0&dr=0&lr=all&cd=0%7C0%7C0%7C0&cv=1&br=2696&bt=1348&cs=0&ds=6&ft=XE5bCq1hmI1LD12NB41vG-UxaiJ6MVF_O5&mime_type=video_mp4&qs=0&rc=Nmc0NDw0OGQ8Ojs7Nmc5O0Bpamlwcjc8PGg7eTMzODczM0BfYC4wMDIyNjQxL18xNWFeYSMyZDNwMGVuMWVfLS1iMTZzcw%3D%3D&l=202305310652160D799AD36B3767662664&btag=e00080000'), cover='https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068/ca605cad20eb4d3dad8d579afcab46ae~noop.image?x-expires=1685599200&x-signature=oTTZ22A0iXAdhpBawFj8IVz8has%3D&s=FEED&se=false&sh=&sc=cover&l=202305310652160D799AD36B3767662664', dynamic_cover='https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/bb237c7ab4d74272be8e824260b6907a_1608680002?x-expires=1685599200&x-signature=a8NRjWjp%2BKfvOeObKMXbzBBwn3Q%3D&s=FEED&se=false&sh=&sc=dynamic_cover&l=202305310652160D799AD36B3767662664', description='kID cUDI oN kID cUDI  > 🧛🏿\u200d♂️🧛🏿\u200d♂️>', statistics=Statistics(likes=1543566, plays=9641964, comments=57069, downloads=15358, shares=2141137, saves=64279), create_time=1608680001, author=Author(unique_id='playboicarti', nickname='playboicarti', avatar='https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/17961639c0042c3c205f9da21a5ac859~c5_1080x1080.webp?x-expires=1685599200&x-signature=h1aFxdPxjPkBzRGvjeOyQllsrKE%3D', id=None, sec_uid='MS4wLjABAAAAM91LHXSoQbzIiQyAKL0LMg43mcyNQ9e32m8LJGKWZdo8RrWz0MveuIZyl0rkWtOs'), music=Music(title='original sound - playboicarti', author='playboicarti', url='https://sf16-ies-music-va.tiktokcdn.com/obj/musically-maliva-obj/6909227953016654598.mp3', cover='https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/17961639c0042c3c205f9da21a5ac859~c5_1080x1080.webp?x-expires=1685599200&x-signature=h1aFxdPxjPkBzRGvjeOyQllsrKE%3D'))]


would be good to expose a generic end point we can hit

```python
def tiktok_request(this, endpoint, extra_params: dict = {}) -> response:
        params = this.get_params(extra_params)
        
        return this.client.get(f'https://www.tiktok.com/{endpoint}?{this.sign(params, this.userAgent)}', headers = this.get_headers(), cookies = this.cookies)
```

and be able to pass

/aweme/v2/discovery/v4/trending/


UPDATE - I noticed this - maybe helpful

```
  def account_info(this) -> response:
        return this.client.get(f'https://www.tiktok.com/passport/web/account/info/', headers = this.get_headers(), cookies = this.cookies)

```

**Comment by wweevv-johndpope** [comment]
I see this guy only has 2 videos. all good. 

<img width="786" alt="Screenshot 2023-05-31 at 5 14 02 pm" src="https://github.com/sheldygg/aiotiktok/assets/109928647/a9c70aad-ae67-4e9d-9471-448b81fd8706">

**Comment by sheldygg** [comment]
https://github.com/xtekky/TikTok-Report-Bot/blob/af7cbe88b499dcd25f03156e9aeac81d50133745/utils/api.py#L123
I repeated this request in my code but I get empty data {"userInfo": {"user": {},"stats": {},"shareMeta": {}}}
so far I don't know what to do

**Comment by wweevv-johndpope** [comment]
I'm not clear too -
you have to run main.py -> it will ask for session id - you can get from chrome > application > cookies 
I couldn't get any results. 

( I saw in your code you have secuid - and can bypass this. so maybe cookies uncessary? )

**Comment by sheldygg** [comment]
in general, the method that is used in my code is also not bad, I just think that it would be better to use api than to get data with a regular expression

**Comment by wweevv-johndpope** [comment]
I'm curious how app gets the videos that it shows. I thought the user feeds would be it - but not apparently. 
I have a access token in my app - but what end point. I might have to look at android debug assembly.
